"""
04_download_census.py — Download Census ZIP-to-CBSA crosswalk data.

Data sources (public, no authentication required):
    1. Census 2020 ZCTA-to-County relationship file
       URL: https://www2.census.gov/geo/docs/maps-data/data/rel2020/zcta520/tab20_zcta520_county20_natl.txt
    2. OMB 2023 CBSA delineation file
       URL: https://www2.census.gov/programs-surveys/metro-micro/geographies/reference-files/2023/delineation-files/list1_2023.xlsx

These files are combined to create a ZIP5 → CBSA code/title crosswalk
used by the geographic mechanism analysis (metro-level audit committee
composition and DEI keyword variation).

Outputs (in Analysis/Data/raw/census/):
    - zip_cbsa.csv          (ZIP5 → CBSA code + title mapping)
    - list1_2023.xlsx       (OMB reference file, preserved for documentation)

NOTE: raw/census/cbsa_revelio_metro.csv is a MANUALLY CURATED mapping of
CBSA codes to Revelio metro_area values. It is NOT regenerated by this
script. If missing, it must be restored from the backup.

Usage:
    python Analysis/pipeline/04_download_census.py
    python Analysis/pipeline/04_download_census.py --force
"""
import sys, os, argparse
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))

import pandas as pd
import requests

from shared.paths import data_dir

OUTPUT_DIR = os.path.join(data_dir, 'raw', 'census')
os.makedirs(OUTPUT_DIR, exist_ok=True)

ZCTA_URL = 'https://www2.census.gov/geo/docs/maps-data/data/rel2020/zcta520/tab20_zcta520_county20_natl.txt'
OMB_URL = 'https://www2.census.gov/programs-surveys/metro-micro/geographies/reference-files/2023/delineation-files/list1_2023.xlsx'


def download_file(url, local_path):
    """Download a file from a URL."""
    print(f"  Downloading {url}...")
    resp = requests.get(url, timeout=60)
    resp.raise_for_status()
    with open(local_path, 'wb') as f:
        f.write(resp.content)
    print(f"  Saved: {local_path} ({len(resp.content) / 1024 / 1024:.1f} MB)")


def build_crosswalk(force=False):
    """Build the ZIP5 → CBSA crosswalk from Census and OMB data."""
    output_path = os.path.join(OUTPUT_DIR, 'zip_cbsa.csv')
    if os.path.exists(output_path) and not force:
        print(f"  SKIP (exists): zip_cbsa.csv")
        return

    # Download source files
    zcta_path = os.path.join(OUTPUT_DIR, 'tab20_zcta520_county20_natl.txt')
    omb_path = os.path.join(OUTPUT_DIR, 'list1_2023.xlsx')

    if not os.path.exists(zcta_path) or force:
        download_file(ZCTA_URL, zcta_path)
    if not os.path.exists(omb_path) or force:
        download_file(OMB_URL, omb_path)

    # Parse ZCTA-to-County relationship (pipe-delimited)
    zcta = pd.read_csv(zcta_path, sep='|', dtype=str)
    zcta = zcta[['GEOID_ZCTA5_20', 'GEOID_COUNTY_20']].rename(columns={
        'GEOID_ZCTA5_20': 'zip5',
        'GEOID_COUNTY_20': 'county_fips',
    })

    # Parse OMB CBSA delineation (county → CBSA mapping)
    omb = pd.read_excel(omb_path, dtype=str, skiprows=2)
    omb = omb.rename(columns={
        'FIPS State Code': 'state_fips',
        'FIPS County Code': 'county_code',
        'CBSA Code': 'cbsa_code',
        'CBSA Title': 'cbsa_title',
    })
    omb['county_fips'] = omb['state_fips'] + omb['county_code']
    omb = omb[['county_fips', 'cbsa_code', 'cbsa_title']].dropna(subset=['cbsa_code'])

    # Join: ZIP5 → County → CBSA
    merged = zcta.merge(omb, on='county_fips', how='left')
    result = merged[merged['cbsa_code'].notna()][['zip5', 'cbsa_code', 'cbsa_title']].drop_duplicates()

    result.to_csv(output_path, index=False)
    print(f"  Built zip_cbsa.csv: {len(result):,} ZIP-CBSA pairs")

    # Save OMB reference file


def main():
    parser = argparse.ArgumentParser(description='Download Census crosswalk data')
    parser.add_argument('--force', action='store_true', help='Re-download and rebuild')
    args = parser.parse_args()

    print("=" * 60)
    print("  04_download_census.py — Census ZIP-to-CBSA crosswalk")
    print("=" * 60)

    build_crosswalk(force=args.force)

    # Check for manually curated file
    manual_file = os.path.join(OUTPUT_DIR, 'cbsa_revelio_metro.csv')
    if os.path.exists(manual_file):
        print(f"\n  Manually curated file present: cbsa_revelio_metro.csv")
    else:
        print(f"\n  WARNING: cbsa_revelio_metro.csv not found.")
        print(f"  This file maps CBSA codes to Revelio metro_area values and must be")
        print(f"  restored from backup or manually created.")

    print("\nDone.")


if __name__ == '__main__':
    main()
